

connect to CR;

CREATE BUFFERPOOL large_pool PAGESIZE 32K;
CREATE BUFFERPOOL small_pool PAGESIZE 16K;
CREATE BUFFERPOOL index_pool PAGESIZE 16K;
CREATE BUFFERPOOL temp32k_pool PAGESIZE 32K;
CREATE BUFFERPOOL temp16k_pool PAGESIZE 16K;

CREATE LARGE TABLESPACE TB_ACT_TBL PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL large_pool;
CREATE LARGE TABLESPACE TB_CCA_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_CYC_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_CRD_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_DB_TBL  PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_RSK_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_COL_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_TSC_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_OTH_TBL PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL large_pool;
CREATE LARGE TABLESPACE TB_MKT_TBL PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL large_pool;
CREATE LARGE TABLESPACE TB_BIL_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_BIM_TBL PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL small_pool;
CREATE LARGE TABLESPACE TB_PTR_TBL PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL large_pool;
                                                
CREATE LARGE TABLESPACE TB_ACT_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool;
CREATE LARGE TABLESPACE TB_CCA_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool;
CREATE LARGE TABLESPACE TB_CYC_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_CRD_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_DB_IDX  PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_RSK_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_COL_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_TSC_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_OTH_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_MKT_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_BIL_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_BIM_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 
CREATE LARGE TABLESPACE TB_PTR_IDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL index_pool; 

CREATE SYSTEM TEMPORARY TABLESPACE BP_SYSTEM32K PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL temp32k_pool;
CREATE SYSTEM TEMPORARY TABLESPACE BP_SYSTEM16K PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL temp16k_pool;
CREATE USER   TEMPORARY TABLESPACE BP_USER   PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL temp32k_pool;

------------------------------------------------
-- DDL Statements for Schemas
------------------------------------------------

CREATE SCHEMA "ECSCRDB" AUTHORIZATION "crpinst1";

COMMIT WORK;
CONNECT RESET;
TERMINATE;