connect to cr;

--20201130 

COMMENT ON COLUMN ECSCRDB.CCA_AUTH_TXLOG.EC_FLAG IS ' Reversal旗標';

ALTER TABLE ECSCRDB.CCA_AUTH_SMS2_PARM ALTER WEB3D_FLAG SET DATA TYPE VARCHAR(1);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ECSCRDB.CCA_AUTH_SMS2_PARM');

ALTER TABLE ECSCRDB.CCA_AUTH_SMS2_DETL ALTER WEB3D_FLAG SET DATA TYPE VARCHAR(1);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ECSCRDB.CCA_AUTH_SMS2_DETL');

--20201222 


DROP TABLE "ECSCRDB "."OEMPAY_CARD";
CREATE TABLE "ECSCRDB "."OEMPAY_CARD_LOG"  (
		  "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACNO_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PROG_CODE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RESP_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REASON_DESC" VARGRAPHIC(60 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "EPAY_TYPE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."OEMPAY_CARD_LOG" IS 'EPAY 卡交易log檔' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."ACNO_P_SEQNO" IS '帳戶流水號     ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."CARD_NO" IS '卡號           ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."CRT_DATE" IS '鍵檔日期       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."CRT_TIME" IS '鍵檔時間       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."EPAY_TYPE" IS 'EPAY卡別 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."ID_P_SEQNO" IS '帳戶流水號碼   ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."MOD_PGM" IS '異動程式       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."MOD_TIME" IS '異動時間       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."PROG_CODE" IS '虛擬卡處理進度 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."REASON_DESC" IS '原因說明       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."RESP_CODE" IS '交易結果       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD_LOG"."V_CARD_NO" IS '虛擬卡號       ' ;

CREATE INDEX "ECSCRDB "."OEMPAY_CARD_LOG_IDX_1" ON "ECSCRDB "."OEMPAY_CARD_LOG" 
		("ID_P_SEQNO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."OEMPAY_CARD_LOG_IDX_2" ON "ECSCRDB "."OEMPAY_CARD_LOG" 
		("CARD_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;


GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."OEMPAY_CARD_LOG"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."OEMPAY_CARD_LOG"  TO USER EMDAP41, USER EMDAP42 ;


-- ECSCRDB.OEMPAY_APPLY_DATA definition
DROP TABLE "ECSCRDB"."OEMPAY_APPLY_DATA";
CREATE TABLE "ECSCRDB "."OEMPAY_APPLY_DATA"  (
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "WALLET_ID" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT  , 
		  "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NEW_END_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "T_PAN_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "T_PAN_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RCV_STATUS" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SUBJECT_CODE" VARGRAPHIC(15 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "REASON_CODE" VARGRAPHIC(15 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "SIR_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SIR" VARCHAR(36 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACNO_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_VER_CODE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_VER_MINS" INTEGER NOT NULL WITH DEFAULT  , 
		  "OPT_VER_CNT" INTEGER NOT NULL WITH DEFAULT  , 
		  "OPT_VER_SEND_CNT" INTEGER NOT NULL WITH DEFAULT  , 
		  "OPT_VER_DATETIME" VARCHAR(14 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_S_DATETIME" VARCHAR(14 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_E_DATETIME" VARCHAR(14 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SEND_OPT_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "IDNV_TYPE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NEW_APPLY_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RESET_PSWD_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "EMBOSS_HEAD" VARGRAPHIC(500 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "EMBOSS_DATA" VARGRAPHIC(500 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BATCH_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BATCH_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PROC_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" IS 'EPAY申請檔' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ACNO_P_SEQNO" IS '帳戶流水號             ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."BATCH_DATE" IS '批次日期               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."BATCH_TIME" IS '批次時間               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CARD_NO" IS '卡號                   ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CRT_DATE" IS '鍵檔日期               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CRT_TIME" IS '鍵檔時間               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."EMBOSS_DATA" IS '凸字第四行             ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."EMBOSS_HEAD" IS '製卡檔表頭             ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."IDNV_TYPE" IS 'ID&V的事件類型         ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ID_P_SEQNO" IS '帳戶流水號碼           ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."MOD_PGM" IS '異動程式               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."MOD_TIME" IS '異動時間               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."NEW_APPLY_DATE" IS '新申請卡片下載日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."NEW_END_DATE" IS '虛擬卡號效期           ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_E_DATETIME" IS '驗證日期時間-迄        ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_FLAG" IS '發簡訊驗證旗標         ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_S_DATETIME" IS '驗證日期時間-起        ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_VER_CNT" IS '驗證瑪檢核次數         ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_VER_CODE" IS '簡訊驗證瑪             ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_VER_DATETIME" IS '驗證日期時間           ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_VER_MINS" IS '須完成驗證分鐘         ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."OPT_VER_SEND_CNT" IS '驗證瑪重送次數         ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."PROC_FLAG" IS '處理註記        1:成功 2:退件 3:分期 N:未處理' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."RCV_STATUS" IS '執行狀態               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."REASON_CODE" IS '理由代碼               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."RESET_PSWD_DATE" IS '重設卡片密碼日期       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."SEND_OPT_FLAG" IS '是否需發送OTP給使用者  ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."SIR" IS 'SIR NO                 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."SIR_USER" IS '產生SIR者              ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."SUBJECT_CODE" IS '主體代碼               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."T_PAN_DATE" IS '虛擬卡號產生日期       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."T_PAN_TIME" IS '虛擬卡號產生時間       ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."V_CARD_NO" IS '虛擬卡號               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."WALLET_ID" IS 'WALLET_ID              ' ;

CREATE UNIQUE INDEX "ECSCRDB "."OEMPAY_APPLY_DATA_UK" ON "ECSCRDB "."OEMPAY_APPLY_DATA" 
		("CARD_NO" ASC,
		 "WALLET_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."OEMPAY_APPLY_DATA_IDX_1" ON "ECSCRDB "."OEMPAY_APPLY_DATA" 
		("ACNO_P_SEQNO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."OEMPAY_APPLY_DATA_IDX_2" ON "ECSCRDB "."OEMPAY_APPLY_DATA" 
		("CRT_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."OEMPAY_APPLY_DATA"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."OEMPAY_APPLY_DATA"  TO USER EMDAP41, USER EMDAP42 ;


-- ECSCRDB.CCA_AUTH_BITDATA definition
DROP TABLE "ECSCRDB "."CCA_AUTH_BITDATA";
CREATE TABLE "ECSCRDB "."CCA_AUTH_BITDATA"  (
                     "TX_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "TX_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "TX_DATETIME" TIMESTAMP , 
                     "AUTH_SEQNO" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "MESSAGE_HEAD1" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "MESSAGE_HEAD2" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "MESSAGE_HEAD3" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "MESSAGE_HEAD4" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "MESSAGE_HEAD5" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "MESSAGE_HEAD6" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "TRANS_TYPE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BITMAP" VARCHAR(128 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT2_ACCT_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT3_PROC_CODE" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT4_TRAN_AMT" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT6_BILLING_AMT" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT7_DATE_TIME" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT10_BILLING_RATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT11_AUDIT_NO" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT12_LOCAL_TIME" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT13_LOCAL_DATE" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT14_EXPIRE_DATE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT15_SETL_DATE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT17_CAP_DATE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT18_MCHT_CAT_CODE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT19_ACQ_COUNTRY_CODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT22_POS_ENTRYMODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT25_POS_CONDMODE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT26_PIN_LEN" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT28_TRANS_FEE" VARCHAR(9 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT31_TID" VARCHAR(30 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT32_CODE" VARCHAR(13 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT35_TRACK_II" VARCHAR(37 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT37_REF_NO" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT38_APPR_CODE" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT39_ADJ_CODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT41_TERM_ID" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT43_MCHT_LOC" VARGRAPHIC(40 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
                     "BIT42_CARD_ACCEPTOR_CODE" VARCHAR(15 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT43_CARD_ACCEPTOR_NAME" VARCHAR(60 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT44_ADD_RESP_CODE" VARCHAR(27 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT45_TRACK_I" VARCHAR(100 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT48_ADD_DATA" VARCHAR(79 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT49_TRANS_CUR_CODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT50_CURR_SETL" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT51_CURR_BILL" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT52_PIN_DATA" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT53_SECURITY_INFO" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT54_ADDITIONAL_AMT" VARCHAR(40 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT58_ADDITIONAL_DATA" VARCHAR(300 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT60_POS_INFO" VARCHAR(61 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT61_OTHER_DATA" VARCHAR(26 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT62_POSTAL_CODE" VARCHAR(13 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT63_POS_ADD_DATA" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT66_SETL_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT70_NETWORK" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT73_ACT_DATE" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT74_NO_CREDIT" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT75_REV_NO_CREDIT" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT76_NO_DEBITS" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT77_REV_NO_DEBITS" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT78_NO_TRANSFER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT79_REV_NO_TRANSFER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT80_NO_INQURIES" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT81_NO_AUTH" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT86_AMT_CREDITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT87_REV_AMT_CREDITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT88_AMT_DEBITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT89_REV_AMT_DEBITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT90_ORG_DATA" VARCHAR(42 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT91_FILE_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT95_REPL_AMT" VARCHAR(42 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT97_NET_AMT" VARCHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT99_SETL_INST" VARCHAR(13 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT101_FILE_NAME" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT112_INSTALLMENT_DATA" VARCHAR(27 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT120_MESS_DATA" VARCHAR(153 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT121_ISSUER" VARCHAR(60 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT122_OPEN_DATA" VARCHAR(101 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT123_ADDR_DATA" VARCHAR(153 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT124_TOKEN_DATA" VARCHAR(500 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT125_SUPP_DATA" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT126_CAF_DATA" VARCHAR(44 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT126_ATM_ADD_DATA" VARCHAR(800 OCTETS) NOT NULL WITH DEFAULT '' , 
                     "BIT127_REC_DATA" VARCHAR(200 OCTETS) NOT NULL WITH DEFAULT '' )   
                    IN "TB_CCA_TBL" INDEX IN "TB_CCA_IDX"  
                    ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" IS '授權交易記錄檔' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."AUTH_SEQNO" IS '授權流水號                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT101_FILE_NAME" IS '檔案名稱                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT10_BILLING_RATE" IS '持卡人結帳轉換匯率' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT112_INSTALLMENT_DATA" IS '分期資訊                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT11_AUDIT_NO" IS 'System Trace Audit Number         ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT120_MESS_DATA" IS '最大值153位                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT121_ISSUER" IS 'iso-121               (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT122_OPEN_DATA" IS 'From Host Maintenance I nformation ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT123_ADDR_DATA" IS '線上鍵值交換                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT124_TOKEN_DATA" IS 'TOKEN相關資訊                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT125_SUPP_DATA" IS '清算資料              (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT126_ATM_ADD_DATA" IS 'ATM Additional Data                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT126_CAF_DATA" IS 'CAF 檔案資料                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT127_REC_DATA" IS 'EDC 交易資料                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT12_LOCAL_TIME" IS '交易當地時間                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT13_LOCAL_DATE" IS '交易當地月日                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT14_EXPIRE_DATE" IS '卡片到期月日YYMM                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT15_SETL_DATE" IS '清算月日                          ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT17_CAP_DATE" IS '交易月日(Capture)                 ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT18_MCHT_CAT_CODE" IS '特約商店行業類別碼                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT19_ACQ_COUNTRY_CODE" IS '收單行國家別           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT22_POS_ENTRYMODE" IS 'Point of Service Entry Mode       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT25_POS_CONDMODE" IS 'Point of Service Condition Mode   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT26_PIN_LEN" IS 'PIN Code 長度         (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT28_TRANS_FEE" IS '交易手續費金額                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT2_ACCT_NO" IS '卡號或帳號                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT31_TID" IS '(iso無此欄位)                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT32_CODE" IS '收單機構代碼                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT35_TRACK_II" IS 'TRACK_II 資料                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT37_REF_NO" IS '收行主機識別碼                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT38_APPR_CODE" IS '授權號碼                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT39_ADJ_CODE" IS 'ISO交易回覆碼                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT3_PROC_CODE" IS 'Processing Code                   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT41_TERM_ID" IS 'card terminal ID                   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT42_CARD_ACCEPTOR_CODE" IS '特店代號                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT43_CARD_ACCEPTOR_NAME" IS '端末設備所在地之資訊               ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT43_MCHT_LOC" IS '消費地資料                         ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT44_ADD_RESP_CODE" IS 'Additional Response Dat a          ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT45_TRACK_I" IS 'TRACK-I               (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT48_ADD_DATA" IS 'ATM/POS/Net附加資料                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT49_TRANS_CUR_CODE" IS 'Transaction Currency Co de         ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT4_TRAN_AMT" IS '消費金額' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT50_CURR_SETL" IS '清算幣別              (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT51_CURR_BILL" IS '持卡人結帳幣別              (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT52_PIN_DATA" IS 'PIN 資料                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT53_SECURITY_INFO" IS '網路管理訊息                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT54_ADDITIONAL_AMT" IS '帳戶金額資訊                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT58_ADDITIONAL_DATA" IS '各種業務資訊                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT60_POS_INFO" IS 'POS終端機資料或0300                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT61_OTHER_DATA" IS 'POS發卡行回覆資料                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT62_POSTAL_CODE" IS '特店郵遞區號                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT63_POS_ADD_DATA" IS 'POS Additional Data                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT66_SETL_CODE" IS '對帳回覆訊息                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT6_BILLING_AMT" IS '持卡人結帳金額' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT70_NETWORK" IS '0800交易類別                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT73_ACT_DATE" IS '0300-檔案刪除日期                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT74_NO_CREDIT" IS 'Credit交易筆數                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT75_REV_NO_CREDIT" IS 'Credit沖消交易筆數                 ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT76_NO_DEBITS" IS 'Debit交易筆數                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT77_REV_NO_DEBITS" IS 'Debit沖消交易筆數                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT78_NO_TRANSFER" IS 'Transfer交易筆數                   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT79_REV_NO_TRANSFER" IS 'Transfer沖消交易筆數               ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT7_DATE_TIME" IS '交易傳送日期時間                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT80_NO_INQURIES" IS '查詢交易筆數                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT81_NO_AUTH" IS '授權交易筆數                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT86_AMT_CREDITS" IS 'Credit金額總計                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT87_REV_AMT_CREDITS" IS 'Credit沖消金額總計                 ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT88_AMT_DEBITS" IS 'Debit金額總計                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT89_REV_AMT_DEBITS" IS 'Debit沖消金額總計                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT90_ORG_DATA" IS '原始交易資料                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT91_FILE_CODE" IS '檔案更新                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT95_REPL_AMT" IS '調整金額                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT97_NET_AMT" IS '清算淨額                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT99_SETL_INST" IS '清算銀行代碼                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BITMAP" IS 'ISO8583 字串                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."CARD_NO" IS '卡號                              ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD1" IS 'ISO-head-1                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD2" IS 'ISO-head-2                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD3" IS 'ISO-head-3                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD4" IS 'ISO-head-4                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD5" IS '交易發生端代碼                    ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD6" IS '交易處理單位                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TRANS_TYPE" IS 'ISO-交易類別                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TX_DATE" IS '建檔日期                          ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TX_DATETIME" IS '消費日期時間                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TX_TIME" IS '建檔時間                          ' ;

CREATE INDEX "ECSCRDB "."CCA_AUTH_BITDATA_FK01" ON "ECSCRDB "."CCA_AUTH_BITDATA" 
                   ("CARD_NO" ASC,
                   "TX_DATE" ASC,
                   "TX_TIME" ASC)
                   
                   COMPRESS NO 
                   INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."CCA_AUTH_BITDATA_FK02" ON "ECSCRDB "."CCA_AUTH_BITDATA" 
                   ("AUTH_SEQNO" ASC)
                   
                   COMPRESS NO 
                   INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "EMDAP41 "  ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "EMDAP42 "  ;

GRANT DELETE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

GRANT INSERT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

GRANT ALTER ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT DELETE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT INSERT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

--1231 


DROP INDEX  "ECSCRDB "."CCA_AUTH_TXLOG_IDX15" ; 


--0105 
ALTER TABLE ECSCRDB.CRD_ITEM_UNIT ALTER ISSUER_CONFIGURATION_ID SET DATA TYPE   VARCHAR(8);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ECSCRDB.CRD_ITEM_UNIT');


ALTER TABLE ECSCRDB.CCA_AUTH_TXLOG  DROP COLUMN ORI_TXN_IDF;
CALL SYSPROC.ADMIN_CMD('REORG TABLE ECSCRDB.CCA_AUTH_TXLOG');
--ECSCRDB 

--DROP TABLE ECSCRDB.CCA_IMS_OUTGOING;
CREATE TABLE "ECSCRDB "."CCA_IMS_OUTGOING"  (
		  "HOST_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TXN_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TXN_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FSCODE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TRACK2_DATA" VARCHAR(37 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TX_AMT" DECIMAL(10,0) NOT NULL WITH DEFAULT 0 , 
		  "CHARGE_AMT" DECIMAL(10,0) NOT NULL WITH DEFAULT 0 , 
		  "ORGINAL_AMT" DECIMAL(10,0) NOT NULL WITH DEFAULT 0 , 
		  "ACCOUNT_NO" VARCHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_SEQ" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TX_SEQ" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TRACE_NO" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TRACE_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TRACE_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RET_REF_NO" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TSCC_CRD" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MSG_TYPE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RTN_CODE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TX_TYPE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_SEQNO" DECIMAL(10,0) NOT NULL WITH DEFAULT 0 )   
		 IN "TB_CCA_TBL" INDEX IN "TB_CCA_IDX"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "ECSCRDB "."CCA_IMS_OUTGOING" IS 'IMS 線上VD圈存解圈LOG檔';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."ACCOUNT_NO" IS '帳號';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."ACCT_SEQ" IS '金融卡序號';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."CHARGE_AMT" IS '需圈存、解圈、強圈及扣帳金額(實際金額，含手續費、匯差金額)    ';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."FSCODE" IS '主機交易類別V0(2440)(一般圈存)/V2(2442)(悠遊卡加值圈存)/V7(2447)(預先授權完成、圈存調整)/VA(VDAD)(人工解圈扣帳)/VR(VDRT)(退貨解圈)';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."HOST_SEQNO" IS '由財金或新信用卡系統編的交易序號';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."MOD_PGM" IS '異動程式';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."MOD_SEQNO" IS '異動註記';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."MOD_TIME" IS '異動時間';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."MOD_USER" IS '異動使用者';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."MSG_TYPE" IS '0200-第一趟(REQ) 0202-第二趟(RVS沖正)';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."ORGINAL_AMT" IS 'V7強圈時帶原charge-amt需圈存金額，其餘交易放0';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."RET_REF_NO" IS 'ISO8583 Retrieval Reference Number  ';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."RTN_CODE" IS '由主機回覆，‘0000’表示成功，其它表示失敗';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TRACE_DATE" IS 'ISO8583 交易日期 ';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TRACE_NO" IS 'ISO8583 交易序號';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TRACE_TIME" IS 'ISO8583 交易時間';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TRACK2_DATA" IS '第二軌資料，含VD卡號(左靠右補空白)';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TSCC_CRD" IS '悠遊卡外顯卡號';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TXN_DATE" IS '原交易之交易日期';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TXN_TIME" IS '原交易之交易時間';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TX_AMT" IS '授權金額/交易金額(原消費金額)，人工解圈扣帳時放0';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TX_SEQ" IS '圈存序號(沖正交易時，放入原圈存序號) ';

COMMENT ON COLUMN "ECSCRDB "."CCA_IMS_OUTGOING"."TX_TYPE" IS '沖正交易類別：6-圈存交易；7-解圈交易；8-強圈交易；9-扣帳交易；A-人工圈存；B-人工解圈';

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."CCA_IMS_OUTGOING"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."CCA_IMS_OUTGOING"  TO USER EMDAP41, USER EMDAP42 ;


--DROP TABLE ECSCRDB.CMS_LOUNGE_VISIT;
CREATE TABLE "ECSCRDB "."CMS_LOUNGE_VISIT"  (
		  "CRT_DATE" VARCHAR(8 OCTETS) , 
		  "BIN_TYPE" VARCHAR(1 OCTETS) , 
		  "DATA_SEQNO" INTEGER , 
		  "FROM_TYPE" VARCHAR(1 OCTETS) , 
		  "BANK_NAME" VARCHAR(60 OCTETS) , 
		  "DEAL_TYPE" VARCHAR(30 OCTETS) , 
		  "ASSOCIATE_CODE" VARCHAR(20 OCTETS) , 
		  "ICA_NO" VARCHAR(8 OCTETS) , 
		  "PP_CARD_NO" VARCHAR(20 OCTETS) , 
		  "CH_ENAME" VARGRAPHIC(30 CODEUNITS16) , 
		  "VISIT_DATE" VARCHAR(8 OCTETS) , 
		  "LOUNGE_NAME" VARGRAPHIC(50 CODEUNITS16) , 
		  "LOUNGE_CODE" VARCHAR(10 OCTETS) , 
		  "DOMESTIC_INT" VARCHAR(5 OCTETS) , 
		  "ISO_CONTY" VARCHAR(20 OCTETS) , 
		  "ISO_CONTY_CODE" VARCHAR(5 OCTETS) , 
		  "CH_VISITS" INTEGER , 
		  "GUESTS_COUNT" INTEGER , 
		  "TOTAL_VISITS" INTEGER , 
		  "BATCH_NO" INTEGER , 
		  "VOUCHER_NO" VARCHAR(30 OCTETS) , 
		  "MC_BILLING_REGION" VARCHAR(10 OCTETS) , 
		  "CURR_CODE" VARCHAR(10 OCTETS) , 
		  "FEE_PER_HOLDER" INTEGER , 
		  "FEE_PER_GUEST" INTEGER , 
		  "TOTAL_FEE" INTEGER , 
		  "TOTAL_FREE_GUESTS" INTEGER , 
		  "FREE_GUESTS_VALUE" INTEGER , 
		  "TOT_CHARG_GUEST" INTEGER , 
		  "CHARG_GUEST_VALUE" INTEGER , 
		  "BILLING_REGION" VARCHAR(20 OCTETS) , 
		  "TERMINAL_NO" VARCHAR(30 OCTETS) , 
		  "USE_CITY" VARGRAPHIC(30 CODEUNITS16) , 
		  "ID_NO" VARCHAR(10 OCTETS) , 
		  "ID_NO_CODE" VARCHAR(1 OCTETS) , 
		  "ID_P_SEQNO" VARCHAR(10 OCTETS) , 
		  "FREE_USE_CNT" INTEGER , 
		  "GUEST_FREE_CNT" INTEGER , 
		  "CH_COST_AMT" INTEGER , 
		  "GUEST_COST_AMT" INTEGER , 
		  "CARD_NO" VARCHAR(19 OCTETS) , 
		  "MCHT_NO" VARCHAR(15 OCTETS) , 
		  "USER_REMARK" VARGRAPHIC(60 CODEUNITS16) , 
		  "CRT_USER" VARCHAR(10 OCTETS) , 
		  "IMP_FILE_NAME" VARCHAR(30 OCTETS) , 
		  "MOD_USER" VARCHAR(10 OCTETS) , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) , 
		  "MOD_SEQNO" DECIMAL(10,0) )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "ECSCRDB "."CMS_LOUNGE_VISIT" IS '龍騰卡請款記錄檔';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."ASSOCIATE_CODE" IS 'Associate Code';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."BANK_NAME" IS 'Bank name';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."BATCH_NO" IS 'Batch no';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."BILLING_REGION" IS 'Billing Region';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."BIN_TYPE" IS '卡別';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CARD_NO" IS '卡號';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CHARG_GUEST_VALUE" IS 'Chargeable Guest Value';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CH_COST_AMT" IS '卡友自費金額';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CH_ENAME" IS 'Cardholder Name';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CH_VISITS" IS 'Cardholder Visits';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CRT_DATE" IS '鍵檔日期';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CRT_USER" IS '建檔人員';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."CURR_CODE" IS '幣別';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."DATA_SEQNO" IS '資料序號';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."DEAL_TYPE" IS 'Deal Type';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."DOMESTIC_INT" IS 'Domestic or INT';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."FEE_PER_GUEST" IS 'Fee Per Guest';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."FEE_PER_HOLDER" IS 'Fee Per Member';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."FREE_GUESTS_VALUE" IS 'FREE Guests Value';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."FREE_USE_CNT" IS '免費使用次數';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."FROM_TYPE" IS '資料來源';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."GUESTS_COUNT" IS 'Guests Count';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."GUEST_COST_AMT" IS '非卡友自費金額';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."GUEST_FREE_CNT" IS '非卡友免費次數';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."ICA_NO" IS 'ICA';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."ID_NO" IS '卡人ID';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."ID_NO_CODE" IS '卡人ID識別碼';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."ID_P_SEQNO" IS '卡人流水號';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."IMP_FILE_NAME" IS '資料檔名';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."ISO_CONTY" IS 'ISO Country';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."ISO_CONTY_CODE" IS 'Visit ISO Country Code';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."LOUNGE_CODE" IS 'Lounge Code';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."LOUNGE_NAME" IS 'Lounge Name';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."MCHT_NO" IS '特店代號';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."MC_BILLING_REGION" IS 'MC Billing Region of Issue';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."MOD_PGM" IS '異動程式';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."MOD_SEQNO" IS '異動註記';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."MOD_TIME" IS '異動時間';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."MOD_USER" IS '異動使用者';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."PP_CARD_NO" IS 'Priority Pass Id';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."TERMINAL_NO" IS 'Terminal';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."TOTAL_FEE" IS 'Total Fee';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."TOTAL_FREE_GUESTS" IS 'Total FREE Guests';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."TOTAL_VISITS" IS 'Total Visit Count';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."TOT_CHARG_GUEST" IS 'Total Chargeable Guest';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."USER_REMARK" IS '備註';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."USE_CITY" IS 'City';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."VISIT_DATE" IS 'Visit Date';

COMMENT ON COLUMN "ECSCRDB "."CMS_LOUNGE_VISIT"."VOUCHER_NO" IS 'Voucher Number';

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."CMS_LOUNGE_VISIT"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."CMS_LOUNGE_VISIT"  TO USER EMDAP41, USER EMDAP42 ;



--DROP TABLE ECSCRDB.EPAY_ISSUE_STAT;
CREATE TABLE "ECSCRDB "."EPAY_ISSUE_STAT"  (
		  "TXN_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NUM_OF_CURR" INTEGER NOT NULL WITH DEFAULT  , 
		  "NUM_OF_EFFC" INTEGER NOT NULL WITH DEFAULT  , 
		  "NUM_OF_NEW" INTEGER NOT NULL WITH DEFAULT  , 
		  "NUM_OF_OPPOST" INTEGER NOT NULL WITH DEFAULT  , 
		  "TOT_AMT" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , 
		  "TOT_AMT_F" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , 
		  "TOT_CNT" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , 
		  "TOT_CNT_F" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."EPAY_ISSUE_STAT" IS '虛擬卡發卡統計檔' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."MOD_PGM" IS '異動程式     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."MOD_TIME" IS '異動時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."NUM_OF_CURR" IS '目前發卡數   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."NUM_OF_EFFC" IS '有效發卡數   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."NUM_OF_NEW" IS '新製發卡數   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."NUM_OF_OPPOST" IS '目前發卡數   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."TOT_AMT" IS '國內總金額   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."TOT_AMT_F" IS '國外總金額   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."TOT_CNT" IS '國內處理筆數 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."TOT_CNT_F" IS '國外處理筆數 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_ISSUE_STAT"."TXN_DATE" IS '交易日期     ' ;

CREATE UNIQUE INDEX "ECSCRDB "."EPAY_ISSUE_STAT_PK" ON "ECSCRDB "."EPAY_ISSUE_STAT" 
		("TXN_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."EPAY_ISSUE_STAT"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."EPAY_ISSUE_STAT"  TO USER EMDAP41, USER EMDAP42 ;



--DROP TABLE ECSCRDB.EPAY_LIFE_CYCLE;

CREATE TABLE "ECSCRDB "."EPAY_LIFE_CYCLE"  (
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CURRENT_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPPOST_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPERATION" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RESP_CODE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ERR_MSG" VARGRAPHIC(25 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "PROC_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PROC_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FILE_NAME" VARCHAR(40 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FILE_SEQ" INTEGER NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."EPAY_LIFE_CYCLE" IS '虛擬卡生命週期檔' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."CARD_NO" IS '卡號         ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."CURRENT_CODE" IS '狀態碼        0:正常 1:一般停用 2:掛失 3:強停 4:其他 5: 偽卡' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."ERR_MSG" IS '錯誤訊息     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."FILE_NAME" IS '檔案名稱     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."FILE_SEQ" IS '檔案序號     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."ID_P_SEQNO" IS '帳戶流水號碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."MOD_PGM" IS '異動程式     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."MOD_TIME" IS '異動時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."OPERATION" IS '卡片傳送狀態 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."OPPOST_DATE" IS '停卡日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."PROC_DATE" IS '處理日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."PROC_FLAG" IS '處理註記       1:成功 2:退件 3:分期 N:未處理' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."RESP_CODE" IS '交易結果     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_LIFE_CYCLE"."V_CARD_NO" IS '虛擬卡號     ' ;

CREATE INDEX "ECSCRDB "."EPAY_LIFE_CYCLE_FK1" ON "ECSCRDB "."EPAY_LIFE_CYCLE" 
		("CARD_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_LIFE_CYCLE_FK2" ON "ECSCRDB "."EPAY_LIFE_CYCLE" 
		("ID_P_SEQNO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_LIFE_CYCLE_FK3" ON "ECSCRDB "."EPAY_LIFE_CYCLE" 
		("PROC_FLAG" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_LIFE_CYCLE_FK4" ON "ECSCRDB "."EPAY_LIFE_CYCLE" 
		("FILE_NAME" ASC,
		 "FILE_SEQ" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_LIFE_CYCLE_FK5" ON "ECSCRDB "."EPAY_LIFE_CYCLE" 
		("V_CARD_NO" ASC,
		 "OPPOST_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."EPAY_LIFE_CYCLE"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."EPAY_LIFE_CYCLE"  TO USER EMDAP41, USER EMDAP42 ;



--DROP TABLE ECSCRDB.EPAY_STATUS_ENTRY;

CREATE TABLE "ECSCRDB "."EPAY_STATUS_ENTRY"  (
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NEW_END_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STATUS_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SIR_STATUS" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CHANGE_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "USER_NOTE" VARGRAPHIC(100 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "PROC_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PROC_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "APR_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "APR_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_SEQNO" DECIMAL(10,0) NOT NULL WITH DEFAULT 0 )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."EPAY_STATUS_ENTRY" IS '虛擬卡服務狀態事件紀錄檔' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."APR_DATE" IS '主管覆核日期 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."APR_USER" IS '主管覆核人員 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."CARD_NO" IS '卡號         ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."CHANGE_CODE" IS '卡片狀態        1:暫停 2:恢復  3:中止(人工)' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."CRT_DATE" IS '鍵檔日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."CRT_TIME" IS '鍵檔時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."CRT_USER" IS '建置使用者   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."ID_P_SEQNO" IS '帳戶流水號碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."MOD_PGM" IS '異動程式     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."MOD_SEQNO" IS '異動註記     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."MOD_TIME" IS '異動時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."MOD_USER" IS '異動使用者   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."NEW_END_DATE" IS '本卡有效迄日 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."PROC_DATE" IS '處理日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."PROC_FLAG" IS '處理註記        1:成功 2:退件 3:分期 N:未處理' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."SIR_STATUS" IS 'SIR 目前狀態 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."STATUS_CODE" IS '狀況代號        00:入/扣帳成功 01:存款不足 02:非委託代繳代發戶 03:中止委託代繳代發戶 04:存戶查核資料錯誤 05:無此帳號 06:帳號結清銷戶 07:存款遭強制執行無法代繳 98:其他' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."USER_NOTE" IS '異動備註     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_ENTRY"."V_CARD_NO" IS '虛擬卡號     ' ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_ENTRY_FK_1" ON "ECSCRDB "."EPAY_STATUS_ENTRY" 
		("V_CARD_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_ENTRY_FK_2" ON "ECSCRDB "."EPAY_STATUS_ENTRY" 
		("CARD_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."EPAY_STATUS_ENTRY"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."EPAY_STATUS_ENTRY"  TO USER EMDAP41, USER EMDAP42 ;




--DROP TABLE ECSCRDB.EPAY_STATUS_EVENT;

CREATE TABLE "ECSCRDB "."EPAY_STATUS_EVENT"  (
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SIR_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SIR" VARCHAR(36 OCTETS) NOT NULL WITH DEFAULT  , 
		  "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STATUS_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NEW_END_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPPOST_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "WALLET_ID" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SIR_EVENT" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SIR_STATUS" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACNO_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."EPAY_STATUS_EVENT" IS '虛擬卡狀態事件紀錄檔' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."ACNO_P_SEQNO" IS '帳戶流水號   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."CARD_NO" IS '卡號         ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."CRT_DATE" IS '鍵檔日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."CRT_TIME" IS '鍵檔時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."ID_P_SEQNO" IS '帳戶流水號碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."MOD_PGM" IS '異動程式     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."MOD_TIME" IS '異動時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."NEW_END_DATE" IS '本卡有效迄日 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."OPPOST_DATE" IS '停卡日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."SIR" IS 'SIR          ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."SIR_EVENT" IS 'SIR 事件     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."SIR_STATUS" IS 'SIR 目前狀態 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."SIR_USER" IS '產生SIR者    ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."STATUS_CODE" IS '狀況代號       00:入/扣帳成功 01:存款不足 02:非委託代繳代發戶 03:中止委託代繳代發戶 04:存戶查核資料錯誤 05:無此帳號 06:帳號結清銷戶 07:存款遭強制執行無法代繳 98:其他' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."V_CARD_NO" IS '虛擬卡號     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_EVENT"."WALLET_ID" IS 'WALLET_ID    ' ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_EVENT_FK_1" ON "ECSCRDB "."EPAY_STATUS_EVENT" 
		("SIR_USER" ASC,
		 "SIR" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_EVENT_FK_2" ON "ECSCRDB "."EPAY_STATUS_EVENT" 
		("CARD_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."EPAY_STATUS_EVENT"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."EPAY_STATUS_EVENT"  TO USER EMDAP41, USER EMDAP42 ;



--DROP TABLE ECSCRDB.EPAY_STATUS_REFRESH;

CREATE TABLE "ECSCRDB "."EPAY_STATUS_REFRESH"  (
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "T_PAN_STATUS" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TXN_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TXN_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SE_ID" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MSISDN" VARCHAR(15 OCTETS) NOT NULL WITH DEFAULT  , 
		  "WALLET_NICK" VARCHAR(25 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FILE_NAME" VARCHAR(40 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."EPAY_STATUS_REFRESH" IS '虛擬卡卡片狀態回饋檔' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."CARD_NO" IS '卡號           ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."CRT_DATE" IS '鍵檔日期       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."FILE_NAME" IS '檔案名稱       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."ID_P_SEQNO" IS '帳戶流水號碼   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."MOD_PGM" IS '異動程式       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."MOD_TIME" IS '異動時間       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."MSISDN" IS '行動裝置號碼   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."SE_ID" IS '安全元件識別碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."TXN_DATE" IS '交易日期       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."TXN_TIME" IS '交易時間       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."T_PAN_STATUS" IS '虛擬卡號狀態   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."V_CARD_NO" IS '虛擬卡號       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_REFRESH"."WALLET_NICK" IS '識別碼暱稱     ' ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_REFRESH_FK1" ON "ECSCRDB "."EPAY_STATUS_REFRESH" 
		("CARD_NO" ASC,
		 "TXN_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_REFRESH_FK2" ON "ECSCRDB "."EPAY_STATUS_REFRESH" 
		("ID_P_SEQNO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_REFRESH_FK3" ON "ECSCRDB "."EPAY_STATUS_REFRESH" 
		("V_CARD_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_REFRESH_FK4" ON "ECSCRDB "."EPAY_STATUS_REFRESH" 
		("CRT_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."EPAY_STATUS_REFRESH"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."EPAY_STATUS_REFRESH"  TO USER EMDAP41, USER EMDAP42 ;




--DROP TABLE ECSCRDB.EPAY_STATUS_TXN;
CREATE TABLE "ECSCRDB "."EPAY_STATUS_TXN"  (
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CRT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STATUS_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CHANGE_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FROM_PGM" VARGRAPHIC(20 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "SIR_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SIR" VARCHAR(36 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RCV_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RCV_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RCV_STATUS" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SUBJECT_CODE" VARGRAPHIC(15 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "REASON_CODE" VARGRAPHIC(15 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
		  "PROC_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PROC_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;
		 
COMMENT ON TABLE "ECSCRDB "."EPAY_STATUS_TXN" IS '虛擬卡片狀態傳送紀錄檔' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."CARD_NO" IS '卡號         ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."CHANGE_CODE" IS '變更代號     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."CRT_DATE" IS '鍵檔日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."CRT_TIME" IS '鍵檔時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."FROM_PGM" IS '來源別       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."MOD_PGM" IS '異動程式     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."MOD_TIME" IS '異動時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."PROC_DATE" IS '處理日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."PROC_FLAG" IS '處理註記       1:成功 2:退件 3:分期 N:未處理' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."RCV_DATE" IS '接收日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."RCV_STATUS" IS '接收狀態     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."RCV_TIME" IS '接收時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."REASON_CODE" IS '服務理由代碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."SIR" IS 'SIR          ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."SIR_USER" IS '產生SIR者    ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."STATUS_CODE" IS '狀況代號        00:入/扣帳成功 01:存款不足 02:非委託代繳代發戶 03:中止委託代繳代發戶 04:存戶查核資料錯誤 05:無此帳號 06:帳號結清銷戶 07:存款遭強制執行無法代繳 98:其他' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."SUBJECT_CODE" IS '服務主體代碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_STATUS_TXN"."V_CARD_NO" IS '虛擬卡號     ' ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_TXN_FK_1" ON "ECSCRDB "."EPAY_STATUS_TXN" 
		("CARD_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_STATUS_TXN_FK_2" ON "ECSCRDB "."EPAY_STATUS_TXN" 
		("SIR_USER" ASC,
		 "SIR" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."EPAY_STATUS_TXN"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."EPAY_STATUS_TXN"  TO USER EMDAP41, USER EMDAP42 ;



--DROP TABLE ECSCRDB.EPAY_VER_CODE;

CREATE TABLE "ECSCRDB "."EPAY_VER_CODE"  (
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
		  "WALLET_ID" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACNO_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_VER_CODE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_S_DATETIME" VARCHAR(14 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPT_E_DATETIME" VARCHAR(14 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  )   
		 IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
		 ORGANIZE BY ROW  ;
		 
COMMENT ON TABLE "ECSCRDB "."EPAY_VER_CODE" IS '虛擬卡認證碼紀錄檔' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."ACNO_P_SEQNO" IS '帳戶流水號 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."CARD_NO" IS '卡號       ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."MOD_PGM" IS '異動程式   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."MOD_TIME" IS '異動時間   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."OPT_E_DATETIME" IS '結束時間   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."OPT_S_DATETIME" IS '開始時間   ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."OPT_VER_CODE" IS 'HCE 認證碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."EPAY_VER_CODE"."WALLET_ID" IS 'WALLET_ID  ' ;

CREATE INDEX "ECSCRDB "."EPAY_VER_CODE_FK_1" ON "ECSCRDB "."EPAY_VER_CODE" 
		("CARD_NO" ASC,
		 "OPT_VER_CODE" ASC,
		 "WALLET_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."EPAY_VER_CODE_FK_2" ON "ECSCRDB "."EPAY_VER_CODE" 
		("OPT_VER_CODE" ASC,
		 "CARD_NO" ASC,
		 "WALLET_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."EPAY_VER_CODE"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."EPAY_VER_CODE"  TO USER EMDAP41, USER EMDAP42 ;



--DROP TABLE ECSCRDB.PTR_GINT_DISC;
   

CREATE TABLE "ECSCRDB "."PTR_GINT_DISC"  (
		  "ACCT_TYPE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SUB_TYPE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "GROUP_CODE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CON_MONTH" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "MCODE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INT_RATE" DECIMAL(4,2) NOT NULL WITH DEFAULT 0 , 
		  "CRT_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "APR_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "APR_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "APR_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "MOD_USER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "MOD_SEQNO" DECIMAL(10,0) NOT NULL WITH DEFAULT 0 )   
		 IN "TB_PTR_TBL" INDEX IN "TB_PTR_IDX"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "ECSCRDB "."PTR_GINT_DISC" IS '卡友利息折扣參數檔';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."ACCT_TYPE" IS '帳戶帳號類別碼        01  一般卡02  商務卡03  VISA採購卡05  歡喜卡06  AE卡一般頂/頂級VISA';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."APR_DATE" IS '覆核日期          ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."APR_FLAG" IS '覆核旗標          ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."APR_USER" IS '主管覆核          ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."CON_MONTH" IS 'CON_MONTH         ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."CRT_DATE" IS '建置時間          ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."CRT_USER" IS '建置使用者        ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."GROUP_CODE" IS '團體代號        請參考ptr_group_code';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."INT_RATE" IS '適用之循環息利率  ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."MCODE" IS '逾期繳款月數      ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."MOD_PGM" IS '異動程式          ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."MOD_SEQNO" IS '異動註記          ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."MOD_TIME" IS '異動時間          ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."MOD_USER" IS '異動使用者        ';

COMMENT ON COLUMN "ECSCRDB "."PTR_GINT_DISC"."SUB_TYPE" IS 'SUB_TYPE          ';

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."PTR_GINT_DISC"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."PTR_GINT_DISC"  TO USER EMDAP41, USER EMDAP42 ;

--DROP TABLE ECSCRDB.MOB_TPAN_INFO;
CREATE TABLE "ECSCRDB "."MOB_TPAN_INFO"  (
		  "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TPAN_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TPAN_STATUS" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CRT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "MOD_TIME" TIMESTAMP , 
		  "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' )   
		 IN "TB_TSC_TBL" INDEX IN "TB_TSC_IDX"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "ECSCRDB "."MOB_TPAN_INFO" IS '代碼化交易之虛擬卡資料檔';

COMMENT ON COLUMN "ECSCRDB "."MOB_TPAN_INFO"."CARD_NO" IS '實體卡號   ';

COMMENT ON COLUMN "ECSCRDB "."MOB_TPAN_INFO"."CRT_DATE" IS '鍵檔日期   ';

COMMENT ON COLUMN "ECSCRDB "."MOB_TPAN_INFO"."CRT_TIME" IS '鍵檔時間   ';

COMMENT ON COLUMN "ECSCRDB "."MOB_TPAN_INFO"."MOD_PGM" IS '異動程式   ';

COMMENT ON COLUMN "ECSCRDB "."MOB_TPAN_INFO"."MOD_TIME" IS '異動時間   ';

COMMENT ON COLUMN "ECSCRDB "."MOB_TPAN_INFO"."TPAN_NO" IS '虛擬卡號   ';

COMMENT ON COLUMN "ECSCRDB "."MOB_TPAN_INFO"."TPAN_STATUS" IS '虛擬卡狀態       1: Active，2: Suspended，5: Inactive，4: Deactivated';

GRANT SELECT,INSERT,DELETE,UPDATE ON "ECSCRDB "."MOB_TPAN_INFO"  TO USER CRAP1, USER DCDBMOD ;
GRANT SELECT ON "ECSCRDB "."MOB_TPAN_INFO"  TO USER EMDAP41, USER EMDAP42 ;



terminate;