connect to cr;

--20201130 

COMMENT ON COLUMN ECSCRDB.CCA_AUTH_TXLOG.EC_FLAG IS ' ECI 旗標';

ALTER TABLE ECSCRDB.CCA_AUTH_SMS2_PARM ALTER WEB3D_FLAG SET DATA TYPE VARCHAR(2);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ECSCRDB.CCA_AUTH_SMS2_PARM');

ALTER TABLE ECSCRDB.CCA_AUTH_SMS2_DETL ALTER WEB3D_FLAG SET DATA TYPE VARCHAR(2);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ECSCRDB.CCA_AUTH_SMS2_DETL');

--20201222 

DROP TABLE ECSCRDB.MOB_TPAN_INFO;

DROP TABLE "ECSCRDB "."OEMPAY_CARD";
CREATE TABLE "ECSCRDB "."OEMPAY_CARD"  (
           "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
           "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
           "STATUS_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
           "CHANGE_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "NEW_END_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "EVENT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "EVENT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
           "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
           "ACNO_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
           "ACTIVE_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "EPAY_TYPE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
           "MOD_TIME" TIMESTAMP , 
           "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
           "WALLET_IDENTIFIER" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_PROVIDER" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_ASSURANCE_LEVEL" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_REQUESTOR_ID" VARCHAR(11 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CONTACTLESS_USAGE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "EC_USAGE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MOBILE_EC_USAGE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CORRELATION_ID" VARCHAR(14 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACTIVE_TOKENS" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ISSUE_PRODUCT_ID" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CONSUMER_LANGUAGE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "DEVICE_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
           "FINAL_TOKENIZATION_DECISION" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "FINAL_TOKENIZATION_IND" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "T_C_IDENTIFIER" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
           "T_C_DATE_TIME" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACTIVATION_ATTEMPTS" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_UNIQUE_REF" VARCHAR(48 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACCOUNT_NUMBER_REF" VARCHAR(48 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_TYPE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "WALLET_ID" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "DEVICE_TYPE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' )   
          IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
          ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."OEMPAY_CARD" IS 'EPAY卡檔' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."ACCOUNT_NUMBER_REF" IS 'Service-allocated unique reference to the token. If subfield 23 (Token Type Code) value is F (Card on File)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."ACNO_P_SEQNO" IS '帳戶流水號   ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."ACTIVATION_ATTEMPTS" IS 'Number of activation code entry attempts' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."ACTIVE_DATE" IS '服務佈署日期 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."ACTIVE_TOKENS" IS 'Number of existing active tokens' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."CARD_NO" IS '卡號         ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."CHANGE_DATE" IS '上次換卡日期 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."CONSUMER_LANGUAGE" IS 'Language preference selected by the consumer.' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."CONTACTLESS_USAGE" IS 'Use in contaceless transactions(0:Token is not permitted; 1:Token is permitted)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."CORRELATION_ID" IS 'Identifier assigned by MasterCard' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."CRT_DATE" IS '鍵檔日期     ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."DEVICE_NAME" IS 'Name that the consumer device name' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."DEVICE_TYPE" IS 'Indicates the type of device used' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."EC_USAGE" IS 'Use in card on file EC transactions value(0:Token is not permitted; 1:Token is permitted)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."EPAY_TYPE" IS 'EPAY卡別 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."EVENT_DATE" IS '事件日期        MMDD for V / J / UD, MMDDYY for Master' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."EVENT_TIME" IS '事件時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."FINAL_TOKENIZATION_DECISION" IS 'The final tokenization decision (1:Approve ; 2:Approve but  requires additional authentication)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."FINAL_TOKENIZATION_IND" IS 'Determining the final tokenization decision (1:TE Response; 2:TC Response; 3:issue pre-defined; 4:Mobile Application)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."ID_P_SEQNO" IS '帳戶流水號碼 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."ISSUE_PRODUCT_ID" IS 'The unique card art product configuration identifier provided by the issuer associated' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."MOBILE_EC_USAGE" IS 'Use in card on file EC transactions value(0:Token is not permitted; 1:Token is permitted)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."MOD_PGM" IS '異動程式     ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."MOD_TIME" IS '異動時間     ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."NEW_END_DATE" IS '本卡有效迄日 ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."STATUS_CODE" IS '狀況代號        0.正常; 1.暫停; 2.中止(人工); 3.中止(實體卡停卡); 4.重複取消; 5.中止(已過效期)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."TOKEN_ASSURANCE_LEVEL" IS 'TOKEN保險級數(00~99)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."TOKEN_PROVIDER" IS 'TOKEN 提供者代號 (M:MDES)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."TOKEN_REQUESTOR_ID" IS 'ID assigned by MasterCard to the token requestor' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."TOKEN_TYPE" IS 'Contains a value indicating the type of token.(C:MC Cloud base; F:Card on File; S:Embedded Secure Element)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."TOKEN_UNIQUE_REF" IS 'Service-allocated unique reference to the token. If subfield 23 (Token Type Code) value is F (Card on File), this field will be space filled' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."T_C_DATE_TIME" IS 'specified in UTC units. Format: YYMMDDhhmm' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."T_C_IDENTIFIER" IS 'Identifier associated with the version of terms' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."V_CARD_NO" IS '虛擬卡號     ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."WALLET_IDENTIFIER" IS '錢包種類(101:WALLET REMOTE;102:NFC;103:Apple Pay;216:Android Pay;217:Samsung Pay)' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_CARD"."WALLET_ID" IS 'Contains the identifier associated with the wallet service provider.' ;

CREATE UNIQUE INDEX "ECSCRDB "."OEMPAY_CARD_UK" ON "ECSCRDB "."OEMPAY_CARD" 
         ("V_CARD_NO" ASC, "CARD_NO" ASC)
         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."OEMPAY_CARD_IDX_1" ON "ECSCRDB "."OEMPAY_CARD" 
         ("CARD_NO" ASC)
         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."OEMPAY_CARD_IDX_2" ON "ECSCRDB "."OEMPAY_CARD" 
         ("CRT_DATE" ASC)
         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;


GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "EMDAP41 "  ;

GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "EMDAP42 "  ;

GRANT DELETE ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "DCDBMOD "  ;

GRANT INSERT ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "DCDBMOD "  ;

GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "DCDBMOD "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "DCDBMOD "  ;

GRANT DELETE ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "CRAP1   "  ;

GRANT INSERT ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "CRAP1   "  ;

GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "CRAP1   "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."OEMPAY_CARD" TO USER "CRAP1   "  ;

-- ECSCRDB.OEMPAY_APPLY_DATA definition
DROP TABLE "ECSCRDB"."OEMPAY_APPLY_DATA";
CREATE TABLE "ECSCRDB "."OEMPAY_APPLY_DATA"  (
           "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
           "V_CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT  , 
           "NEW_END_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "ID_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
           "ACNO_P_SEQNO" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
           "CRT_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "CRT_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
           "BATCH_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
           "BATCH_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
           "PROC_FLAG" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
           "MOD_TIME" TIMESTAMP , 
           "MOD_PGM" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
           "TOKEN_MESG_TYPE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CORRELATION_ID" VARCHAR(14 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACCOUNT_SOURCE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACCT_INSTANCE_ID" VARCHAR(48 OCTETS) NOT NULL WITH DEFAULT '' , 
           "DEVICE_IP" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
           "WALLET_ID_HASH" VARCHAR(64 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CARDHOLDER_NAME" VARCHAR(27 OCTETS) NOT NULL WITH DEFAULT '' , 
           "RECOMMENDATION" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "RECOMMEND_VERISON" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "DEVICE_SCORE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACCOUNT_SCORE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "NUMBER_OF_ACTIVE_TOKEN" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "WALLET_REASON_CODE" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
           "DEVICE_LOCATION" VARCHAR(9 OCTETS) NOT NULL WITH DEFAULT '' , 
           "NUMBER_LAST_4_DIGITS" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_TYPE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_TRANSACTION_TYPE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_PROVIDER" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ASSURANCE_LEVEL" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_REQUESTOR_ID" VARCHAR(11 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CONTACTLESS_USAGE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "EC_USAGE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MOBILE_USAGE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ISSUE_PRODUCT_ID" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CONSUMER_LANGUAGE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "DEVICE_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
           "FINAL_DECISION" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "FINAL_IND" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "T_C_INDENTIFIER" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
           "T_C_DATE_TIME" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACTIVE_ATTEMPTS" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_UNIQUE_REF" VARCHAR(48 OCTETS) NOT NULL WITH DEFAULT '' , 
           "ACCOUNT_NUMBER_REF" VARCHAR(48 OCTETS) NOT NULL WITH DEFAULT '' , 
           "WALLET_ID" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "DEVICE_TYPE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_EVENT" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TOKEN_EVENT_REASON" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "EVENT_REQUESTOR" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' )   
          IN "TB_OTH_TBL" INDEX IN "TB_OTH_IDX"  
          ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" IS 'EPAY申請檔' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ACCOUNT_NUMBER_REF" IS 'MTCN Primary Account Number Unique Reference' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ACCOUNT_SCORE" IS 'MTAR_ACCOUNT_SCORE' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ACCOUNT_SOURCE" IS 'MTAR_ACCOUNT_SOURCE' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ACCT_INSTANCE_ID" IS 'MTAR_ACCT_INSTANCE_ID' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ACNO_P_SEQNO" IS '帳戶流水號             ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ACTIVE_ATTEMPTS" IS 'MTCN Number of Activation Attempts' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ASSURANCE_LEVEL" IS 'MTCN Token Assurance Level' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."BATCH_DATE" IS '批次日期               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."BATCH_TIME" IS '批次時間               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CARDHOLDER_NAME" IS 'MTAR_CARDHOLDER_NAME' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CARD_NO" IS '卡號                   ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CONSUMER_LANGUAGE" IS 'MTCN Consumer Language' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CONTACTLESS_USAGE" IS 'MTCN Contactless Usage' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CORRELATION_ID" IS 'MTAR_CORRELATION_ID' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CRT_DATE" IS '鍵檔日期               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."CRT_TIME" IS '鍵檔時間               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."DEVICE_IP" IS 'MTAR_DEVICE_IP' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."DEVICE_LOCATION" IS 'MTAR_DEVICE_LOCATION' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."DEVICE_NAME" IS 'MTCN Device Name' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."DEVICE_SCORE" IS 'MTAR_DEVICE_SCORE' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."DEVICE_TYPE" IS 'MTCN Device Type' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."EC_USAGE" IS 'MTCN Card on File Electronic Commerce Usage' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."EVENT_REQUESTOR" IS 'MTEN Event Requestor' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."FINAL_DECISION" IS 'MTCN Final Tokenization Decision' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."FINAL_IND" IS 'MTCN Final Tokenization Decision Indicator' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ID_P_SEQNO" IS '帳戶流水號碼           ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."ISSUE_PRODUCT_ID" IS 'MTCN Issuer Product Configuration ID' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."MOBILE_USAGE" IS 'MTCN Mobile/Digital Wallet Electronic Commerce Usage' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."MOD_PGM" IS '異動程式               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."MOD_TIME" IS '異動時間               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."NEW_END_DATE" IS '虛擬卡號效期           ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."NUMBER_LAST_4_DIGITS" IS 'MTAR_NUMBER_LAST_4_DIGITS' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."NUMBER_OF_ACTIVE_TOKEN" IS 'MTAR_NUMBER_OF_ACTIVE_TOKEN' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."PROC_FLAG" IS '處理註記        1:成功 2:退件 3:分期 N:未處理' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."RECOMMENDATION" IS 'MTAR_RECOMMEND_ATION' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."RECOMMEND_VERISON" IS 'MTAR_RECOMMEND_VERISON' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_EVENT" IS 'MTEN Tokenization Event Indicator' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_EVENT_REASON" IS 'MTEN Tokenization Event Reason Code' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_MESG_TYPE" IS 'MTAR_TOKEN_MESG_TYPE' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_PROVIDER" IS 'MTCN Token Service Provider' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_REQUESTOR_ID" IS 'MTCN Token Requestor ID' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_TRANSACTION_TYPE" IS 'Token 交 易類型' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_TYPE" IS 'MTAR_TOKEN_TYPE' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."TOKEN_UNIQUE_REF" IS 'MTCN Token Unique Reference' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."T_C_DATE_TIME" IS 'MTCN T&C Date and Time' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."T_C_INDENTIFIER" IS 'MTCN T&C Identifier' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."V_CARD_NO" IS '虛擬卡號               ' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."WALLET_ID" IS 'MTCN Wallet ID' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."WALLET_ID_HASH" IS 'MTAR_WALLET_ID_HASH' ;

COMMENT ON COLUMN "ECSCRDB "."OEMPAY_APPLY_DATA"."WALLET_REASON_CODE" IS 'MTAR_WALLET_REASON_CODE' ;

CREATE INDEX "ECSCRDB "."OEMPAY_APPLY_DATA_IDX_1" ON "ECSCRDB "."OEMPAY_APPLY_DATA" 
         ("CARD_NO" ASC)
         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."OEMPAY_APPLY_DATA_IDX_2" ON "ECSCRDB "."OEMPAY_APPLY_DATA" 
         ("CRT_DATE" ASC)
         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "EMDAP41 "  ;

GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "EMDAP42 "  ;

GRANT DELETE ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "CRAP1   "  ;

GRANT INSERT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "CRAP1   "  ;

GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "CRAP1   "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "CRAP1   "  ;

GRANT DELETE ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "DCDBMOD "  ;

GRANT INSERT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "DCDBMOD "  ;

GRANT SELECT ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "DCDBMOD "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."OEMPAY_APPLY_DATA" TO USER "DCDBMOD "  ;


-- ECSCRDB.CCA_AUTH_BITDATA definition
DROP TABLE "ECSCRDB "."CCA_AUTH_BITDATA";
CREATE TABLE "ECSCRDB "."CCA_AUTH_BITDATA"  (
           "TX_DATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TX_TIME" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TX_DATETIME" TIMESTAMP , 
           "AUTH_SEQNO" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
           "CARD_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MESSAGE_HEAD1" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MESSAGE_HEAD2" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MESSAGE_HEAD3" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MESSAGE_HEAD4" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MESSAGE_HEAD5" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "MESSAGE_HEAD6" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "TRANS_TYPE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BITMAP" VARCHAR(128 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT2_ACCT_NO" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT3_PROC_CODE" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT4_TRAN_AMT" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT6_BILLING_AMT" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT7_DATE_TIME" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT10_BILLING_RATE" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT11_AUDIT_NO" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT12_LOCAL_TIME" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT13_LOCAL_DATE" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT14_EXPIRE_DATE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT15_SETL_DATE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT17_CAP_DATE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT18_MCHT_CAT_CODE" VARCHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT19_ACQ_COUNTRY_CODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT22_POS_ENTRYMODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT25_POS_CONDMODE" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT26_PIN_LEN" VARCHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT28_TRANS_FEE" VARCHAR(9 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT31_TID" VARCHAR(30 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT32_CODE" VARCHAR(13 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT35_TRACK_II" VARCHAR(37 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT37_REF_NO" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT38_APPR_CODE" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT39_ADJ_CODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT41_TERM_ID" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT43_MCHT_LOC" VARGRAPHIC(40 CODEUNITS16) NOT NULL WITH DEFAULT '' , 
           "BIT42_CARD_ACCEPTOR_CODE" VARCHAR(15 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT43_CARD_ACCEPTOR_NAME" VARCHAR(60 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT44_ADD_RESP_CODE" VARCHAR(27 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT45_TRACK_I" VARCHAR(100 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT48_ADD_DATA" VARCHAR(79 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT49_TRANS_CUR_CODE" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT50_CURR_SETL" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT51_CURR_BILL" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT52_PIN_DATA" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT53_SECURITY_INFO" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT54_ADDITIONAL_AMT" VARCHAR(40 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT58_ADDITIONAL_DATA" VARCHAR(300 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT60_POS_INFO" VARCHAR(61 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT61_OTHER_DATA" VARCHAR(26 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT62_POSTAL_CODE" VARCHAR(13 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT63_POS_ADD_DATA" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT66_SETL_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT70_NETWORK" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT73_ACT_DATE" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT74_NO_CREDIT" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT75_REV_NO_CREDIT" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT76_NO_DEBITS" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT77_REV_NO_DEBITS" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT78_NO_TRANSFER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT79_REV_NO_TRANSFER" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT80_NO_INQURIES" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT81_NO_AUTH" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT86_AMT_CREDITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT87_REV_AMT_CREDITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT88_AMT_DEBITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT89_REV_AMT_DEBITS" VARCHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT90_ORG_DATA" VARCHAR(42 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT91_FILE_CODE" VARCHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT95_REPL_AMT" VARCHAR(42 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT97_NET_AMT" VARCHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT99_SETL_INST" VARCHAR(13 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT101_FILE_NAME" VARCHAR(19 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT112_INSTALLMENT_DATA" VARCHAR(27 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT120_MESS_DATA" VARCHAR(500 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT121_ISSUER" VARCHAR(60 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT122_OPEN_DATA" VARCHAR(101 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT123_ADDR_DATA" VARCHAR(153 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT124_TOKEN_DATA" VARCHAR(500 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT125_SUPP_DATA" VARCHAR(12 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT126_CAF_DATA" VARCHAR(44 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT126_ATM_ADD_DATA" VARCHAR(200 OCTETS) NOT NULL WITH DEFAULT '' , 
           "BIT127_REC_DATA" VARCHAR(200 OCTETS) NOT NULL WITH DEFAULT '' )   
          IN "TB_CCA_TBL" INDEX IN "TB_CCA_IDX"  
          ORGANIZE BY ROW  ;

COMMENT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" IS '授權交易記錄檔' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."AUTH_SEQNO" IS '授權流水號                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT101_FILE_NAME" IS '檔案名稱                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT10_BILLING_RATE" IS '持卡人結帳轉換匯率' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT112_INSTALLMENT_DATA" IS '分期資訊' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT11_AUDIT_NO" IS 'System Trace Audit Number         ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT120_MESS_DATA" IS 'File update & administrator advice' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT121_ISSUER" IS 'iso-121               (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT122_OPEN_DATA" IS 'From Host Maintenance I nformation ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT123_ADDR_DATA" IS '線上鍵值交換                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT124_TOKEN_DATA" IS 'TOKEN相關資訊                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT125_SUPP_DATA" IS '清算資料              (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT126_ATM_ADD_DATA" IS 'ATM Additional Data                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT126_CAF_DATA" IS 'CAF 檔案資料                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT127_REC_DATA" IS 'EDC 交易資料                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT12_LOCAL_TIME" IS '交易當地時間                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT13_LOCAL_DATE" IS '交易當地月日                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT14_EXPIRE_DATE" IS '卡片到期月日YYMM                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT15_SETL_DATE" IS '清算月日                          ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT17_CAP_DATE" IS '交易月日(Capture)                 ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT18_MCHT_CAT_CODE" IS '特約商店行業類別碼                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT19_ACQ_COUNTRY_CODE" IS '收單行國家別           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT22_POS_ENTRYMODE" IS 'Point of Service Entry Mode       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT25_POS_CONDMODE" IS 'Point of Service Condition Mode   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT26_PIN_LEN" IS 'PIN Code 長度         (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT28_TRANS_FEE" IS '交易手續費金額                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT2_ACCT_NO" IS '卡號或帳號                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT31_TID" IS '(iso無此欄位)                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT32_CODE" IS '收單機構代碼                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT35_TRACK_II" IS 'TRACK_II 資料                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT37_REF_NO" IS '收行主機識別碼                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT38_APPR_CODE" IS '授權號碼                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT39_ADJ_CODE" IS 'ISO交易回覆碼                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT3_PROC_CODE" IS 'Processing Code                   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT41_TERM_ID" IS 'card terminal ID                   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT42_CARD_ACCEPTOR_CODE" IS '特店代號                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT43_CARD_ACCEPTOR_NAME" IS '端末設備所在地之資訊               ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT43_MCHT_LOC" IS '消費地資料                         ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT44_ADD_RESP_CODE" IS 'Additional Response Dat a          ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT45_TRACK_I" IS 'TRACK-I               (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT48_ADD_DATA" IS 'ATM/POS/Net附加資料                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT49_TRANS_CUR_CODE" IS 'Transaction Currency Co de         ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT4_TRAN_AMT" IS '消費金額' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT50_CURR_SETL" IS '清算幣別              (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT51_CURR_BILL" IS '持卡人結帳幣別              (iso無此欄位)' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT52_PIN_DATA" IS 'PIN 資料                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT53_SECURITY_INFO" IS '網路管理訊息                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT54_ADDITIONAL_AMT" IS '帳戶金額資訊                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT58_ADDITIONAL_DATA" IS '各種業務資訊                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT60_POS_INFO" IS 'POS終端機資料或0300                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT61_OTHER_DATA" IS 'POS發卡行回覆資料                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT62_POSTAL_CODE" IS '特店郵遞區號                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT63_POS_ADD_DATA" IS 'POS Additional Data                ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT66_SETL_CODE" IS '對帳回覆訊息                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT6_BILLING_AMT" IS '持卡人結帳金額' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT70_NETWORK" IS '0800交易類別                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT73_ACT_DATE" IS '0300-檔案刪除日期                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT74_NO_CREDIT" IS 'Credit交易筆數                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT75_REV_NO_CREDIT" IS 'Credit沖消交易筆數                 ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT76_NO_DEBITS" IS 'Debit交易筆數                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT77_REV_NO_DEBITS" IS 'Debit沖消交易筆數                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT78_NO_TRANSFER" IS 'Transfer交易筆數                   ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT79_REV_NO_TRANSFER" IS 'Transfer沖消交易筆數               ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT7_DATE_TIME" IS '交易傳送日期時間                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT80_NO_INQURIES" IS '查詢交易筆數                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT81_NO_AUTH" IS '授權交易筆數                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT86_AMT_CREDITS" IS 'Credit金額總計                     ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT87_REV_AMT_CREDITS" IS 'Credit沖消金額總計                 ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT88_AMT_DEBITS" IS 'Debit金額總計                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT89_REV_AMT_DEBITS" IS 'Debit沖消金額總計                  ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT90_ORG_DATA" IS '原始交易資料                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT91_FILE_CODE" IS '檔案更新                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT95_REPL_AMT" IS '調整金額                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT97_NET_AMT" IS '清算淨額                           ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BIT99_SETL_INST" IS '清算銀行代碼                       ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."BITMAP" IS 'ISO8583 字串                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."CARD_NO" IS '卡號                              ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD1" IS 'ISO-head-1                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD2" IS 'ISO-head-2                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD3" IS 'ISO-head-3                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD4" IS 'ISO-head-4                        ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD5" IS '交易發生端代碼                    ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."MESSAGE_HEAD6" IS '交易處理單位                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TRANS_TYPE" IS 'ISO-交易類別                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TX_DATE" IS '建檔日期                          ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TX_DATETIME" IS '消費日期時間                      ' ;

COMMENT ON COLUMN "ECSCRDB "."CCA_AUTH_BITDATA"."TX_TIME" IS '建檔時間                          ' ;

CREATE INDEX "ECSCRDB "."CCA_AUTH_BITDATA_IDX01" ON "ECSCRDB "."CCA_AUTH_BITDATA" 
         ("CARD_NO" ASC,
         "TX_DATE" ASC,
         "TX_TIME" ASC)
         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "ECSCRDB "."CCA_AUTH_BITDATA_IDX02" ON "ECSCRDB "."CCA_AUTH_BITDATA" 
         ("AUTH_SEQNO" ASC)
         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "EMDAP41 "  ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "EMDAP42 "  ;

GRANT DELETE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT INSERT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "CRAP1   "  ;

GRANT DELETE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

GRANT INSERT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

GRANT SELECT ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

GRANT UPDATE ON TABLE "ECSCRDB "."CCA_AUTH_BITDATA" TO USER "DCDBMOD "  ;

--1231 
CREATE INDEX "ECSCRDB "."CCA_AUTH_TXLOG_IDX15" ON "ECSCRDB "."CCA_AUTH_TXLOG" 
         ("AUTH_SEQNO" ASC)         
         COMPRESS NO 
         INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT USAGE  ON SEQUENCE "ECSCRDB"."SEQ_AUTH_SEQNO"  TO USER "CRAP1"  ;

--0105 
ALTER TABLE ECSCRDB.CRD_ITEM_UNIT ALTER ISSUER_CONFIGURATION_ID SET DATA TYPE   VARCHAR(10);
CALL SYSPROC.ADMIN_CMD('REORG TABLE ECSCRDB.CRD_ITEM_UNIT');


--0118 
ALTER TABLE ECSCRDB.CCA_AUTH_TXLOG ADD ORI_TXN_IDF VARCHAR(15) DEFAULT '';
COMMENT ON COLUMN ECSCRDB.CCA_AUTH_TXLOG.ORI_TXN_IDF IS '原始交易識別碼';

--ECSCRDB 

COMMENT ON TABLE ECSCRDB.CNV_ACNO_SEQNO IS '帳戶序號代碼檔';

COMMENT ON TABLE ECSCRDB.CNV_CARD_CURR IS '轉檔雙幣卡資料檔';

COMMENT ON TABLE ECSCRDB.CNV_CORP_SEQNO IS '統編序號代碼檔';

--ECSCRDB 

DROP TABLE ECSCRDB.CCA_IMS_OUTGOING;

DROP TABLE ECSCRDB.CMS_LOUNGE_VISIT;

DROP TABLE ECSCRDB.EPAY_ISSUE_STAT;

DROP TABLE ECSCRDB.EPAY_LIFE_CYCLE;

DROP TABLE ECSCRDB.EPAY_STATUS_ENTRY;

DROP TABLE ECSCRDB.EPAY_STATUS_EVENT;

DROP TABLE ECSCRDB.EPAY_STATUS_REFRESH;

DROP TABLE ECSCRDB.EPAY_STATUS_TXN;

DROP TABLE ECSCRDB.EPAY_VER_CODE;

--DROP TABLE ECSCRDB.MOB_TPAN_INFO;

DROP TABLE ECSCRDB.PTR_GINT_DISC;
   

terminate;